<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function shift_bezoeker_theme($existing, $type, $theme, $path) {
  return [
    'qr_code' => [
      'variables' => [
        'qr_image' => '',
        'user_name' => '',
        'user_uuid' => '',
        'error' => FALSE,
      ],
      'template' => 'qr-code',
      'path' => $path . '/templates',
      'libraries' => [
        'shift_theme/global-styling',
        'shift_theme/fonts',
      ],
    ],
    'bezoeker_bedrijven' => [
      'variables' => ['bedrijven' => NULL],
      'template' => 'bezoeker-bedrijven',
      'path' => $path . '/templates',
    ],
    'sessie_overzicht_template' => [
      'variables' => [
        'current_date' => NULL,
        'day_number' => NULL,
        'prev_date_url' => NULL,
        'next_date_url' => NULL,
        'locations' => [],
        'time_labels' => [],
        'grid_sessions' => [],
      ],
    ],
    'account_gegevens_template' => [
      'variables' => [
        'user' => NULL,
      ],
    ],
    'inschrijving_bevestigd' => [
      'variables' => [
        'session_id' => NULL,
        'session_title' => NULL,
      ],
    ],
    'home_template' => [
      'variables' => [],
    ],
    'account_verwijderd' => [
      'variables' => [],
      'template' => 'account-verwijderd',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function shift_bezoeker_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attributes']['class'][] = 'shift-styled-form';
}
