<?php

/**
 * Implements hook_theme().
 */
function shift_bezoeker_theme($existing, $type, $theme, $path) {
  return [
    'sessie_overzicht_template' => [
      'variables' => [
        'current_date' => NULL,
        'day_number' => NULL,
        'time_slots' => [],
        'stages' => [],
        'grid_data' => [],
      ],
    ],
    'account_gegevens_template' => [
      'variables' => [
        'user' => NULL,
      ],
    ],
    'inschrijving_bevestigd' => [
      'variables' => [
        'session_id' => NULL,
      ],
    ],
    'home_template' => [
      'variables' => [],
    ],

    'bezoeker_bedrijven' => [
          'variables' => ['bedrijven' => NULL],
        ],
  ];
}