<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function shift_bezoeker_theme($existing, $type, $theme, $path) {
  return [
    'bezoeker_bedrijven' => [
      'variables' => ['bedrijven' => NULL],
      'template' => 'bezoeker-bedrijven',
      'path' => $path . '/templates',
    ],
    'sessie_overzicht_template' => [
      'variables' => [
        'current_date' => NULL,
        'day_number' => NULL,
        'time_slots' => [],
        'stages' => [],
        'grid_data' => [],
      ],
    ],
    'account_gegevens_template' => [
      'variables' => [
        'user' => NULL,
      ],
    ],
    'inschrijving_bevestigd' => [
      'variables' => [
        'session_id' => NULL,
      ],
    ],
    'home_template' => [
      'variables' => [],
    ],
    'bezoeker_bedrijven' => [
      'variables' => ['bedrijven' => NULL],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function shift_bezoeker_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attributes']['class'][] = 'shift-styled-form';
}